### ISSUE TITLE
Refresh data with useTransition (Concurrent mode)

### ISSUE THREAD

**Issue by laggingreflex** [overlookmotel/react-lazy-data#33]
I'm trying to use [useTransition][1] to update the resource. 

Here's a simple example (continuation from my last issue #32)

The button triggers a dummy resource get, which I wanna refresh whenever it's clicked. 

I'm updating  the `state` passed to `Resource.use` to re-trigger the api request. 

And it works as expected in the usual scenario, just not when I involve `useTransition`, or rather, the actual update doesn't work - I think `useTransition` is working correctly, because its `isPending` is working as expected...

```jsx
const { useTransition } = require('react')
const Resource = createResourceFactory(async props => props, { id: 'post' })
function Suspended(props) {
  const [state, update] = useState({text: 'Click Me'})
  const resource = Resource.use(state)
  return <Suspense fallback="Loading"> 
    <App resource={resource} update={update}> 
  </Suspense>
}

function App({ resource, update }) {
  const [startTransition, isPending] = useTransition({ timeoutMs: 3000 });
  const data = resource.read()
  return <button
    disabled={isPending} 
    onClick={
      () => {
        /* It works when I update directly: */
        // update({text: 'Clicked!'})

        /* But not when I update inside useTransition: */
        useTransition(() => {
          update({text: 'Clicked'})
          /* I know this is called because the following logs */
          console.log('This reached')
        })
      }
    }
    /* isPending also works as expected */
  > {isPending ? 'Loading...' : data.text} </button>
}
```

Anything I'm missing or doing wrong? 

Edit: Weird. It works with React@0.0.0-experimental-94c0244ba, not with the current 0.0.0-experimental-4ead6b530. Closing. 

[1]: https://reactjs.org/docs/concurrent-mode-patterns.html#transitions

**Comment by overlookmotel** [comment]
You got it working? Or you gave up?

**Comment by laggingreflex** [comment]
I got it working. The react version I was using (0.0.0-experimental-4ead6b530) was probably faulty or something (it's experimental after all). I switched the version to 0.0.0-experimental-94c0244ba and it worked as-is. Thanks for checking!
